### ISSUE TITLE
Update zerobin to 1.3.3 version ?

### ISSUE THREAD

**Issue by webafrancois** [YunoHost-Apps/zerobin_ynh#33]
The 1.1.1 version is dated to 2017.

The update to 1.3.3 version comes with many translations :
- Ukrainian
- Bulgarian
- Czech
- Russian update
- Spanish,
- Occitan, 
- Norwegian, 
- Portuguese, 
- Dutch 
- Hungarian
https://github.com/PrivateBin/PrivateBin/blob/master/CHANGELOG.md

The default template show the send button to the right end and in the smartphone, it's not visible because hidden by the hamburger menu.
The navbar menu in th 1.1.1 version is very large in wide screen like here : 
https://secret.cemea.org/
and in the 1.3.3 version, all the screen is used.
https://privatebin.net/
Try it on a smartphone...

Thanks a lot.

Or maybe the requirements is so strong to the actual version of Yunohost ?

**Comment by maniackcrudelis** [comment]
There was indeed a lot of releases since 1.1.1, unfortunately that package does not have any dedicated maintainer.
That's the reason why it didn't get upgraded since.

Unfortunately, it's going to be worse https://forum.yunohost.org/t/about-the-end-of-official-apps-in-yunohost/10530. Unless someone is ready to give some love to this app.

**Comment by lapineige** [comment]
Well, I'm using it, and I can spend some time upgrading it if it's just a matter of version URL change and that basic stuff. But I won't have time/be able to go deeper with this package, nor make sure all security stuff is rock solid.

**Comment by webafrancois** [comment]
I'm also interested to take some time to help for upgrade and maintainer this package. I'm sure that zerobin / Pastebin is a goot tool to help users to preserve security.
@maniackcrudelis , have you some time to help us to upgrade this package ?
Can you show us the good documentation to discover the Yunohost packaging ?
https://yunohost.org/#/packaging_apps
And this for french maintainer : https://yunohost.org/#/packaging_apps_start_fr

**Comment by maniackcrudelis** [comment]
What a good news !

The first place to start is indeed https://yunohost.org/#/packaging_apps_start_fr ([or its english version](https://yunohost.org/#/packaging_apps_start)), and especially the apps xmpp room with a lot of people that can help.
@lapineige already knows quite a lot about it as well.

I agree that Pastebin is a good tool, I use it myself and would love to see it maintained.

NB: For what I'm concerned and because you mentioned it, here or on the xmpp room don't hesitate to use French if you're more comfortable with it. I rather prefer that people ask questions in french or any other language than to stay quiet to not make mistake in English.

**Comment by lapineige** [comment]
And mistakes are fine anyway, everyone do make mistake, that's not a big deal :)
Also we can help to translate if needed :)

**Comment by nqb** [comment]
Hello,

I supposed this issue can be closed according to #34. Maybe instance that host YunoHost demo can be upgraded to 1.3.4 to reflect changes.

**Comment by ericgaspar** [comment]
closing with #34
